### PR TITLE
Keep Inline HTML tags in the translated text group while ignoring block level HTML tags

### LINKED ISSUE #125: Wrong normalization of message with HTML
This is from https://github.com/google/comprehensive-rust/issues/1471: running `mdbook-i18n-normalize` on a translated message that contain HTML gives the wrong output.

I can reproduce this with

```patch
diff --git a/i18n-helpers/src/normalize.rs b/i18n-helpers/src/normalize.rs
index 7fed94d..4c0fd5c 100644
--- a/i18n-helpers/src/normalize.rs
+++ b/i18n-helpers/src/normalize.rs
@@ -451,6 +451,15 @@ mod tests {
         );
     }
 
+    #[test]
+    fn test_normalize_html() {
+        let catalog = create_catalog(&[("foo <span>bar</span>", "FOO <span>BAR</span>")]);
+        assert_normalized_messages_eq(
+            catalog,
+            &[exact("foo <span>bar</span>", "FOO <span>BAR</span>")],
+        );
+    }
+
     #[test]
     fn test_normalize_disappearing_html() {
         // Normalizing "<b>" results in no messages.
```

This tests normalizing a catalog looking like this:

```po
msgid "foo <span>bar</span>"
msgstr "FOO <span>BAR</span>"
```

The test fails with

```
---- normalize::tests::test_normalize_html stdout ----
thread 'normalize::tests::test_normalize_html' panicked at i18n-helpers/src/normalize.rs:457:9:
assertion failed: `(left == right)`

Diff < left / right > :
 [
     (
         false,
<        "foo ",
<        "FOO ",
<    ),
<    (
<        false,
<        "bar",
<        "BAR",
>        "foo <span>bar</span>",
>        "FOO <span>BAR</span>",
     ),
 ]
```

which tells us that the normalized catalog contain _two_ messages:

```po
msgid "foo"
msgstr "FOO"

msgid "bar"
msgstr "BAR"
```

In other words, the original message was split into two messages.

In case only the translation contain HTML, the normalization will end up with a different number of messages: 1 for the `msgid` field, and 2 for the `msgstr` field. This is seen as an error, so a fallback kicks in: the normalized message is marked fuzzy and we accumulate the "left-over" messages into the final message.

This behavior can be seen in this unit test in `normalize.rs`:

```rust
    #[test]
    fn test_normalize_fuzzy_list_items_too_many() {
        let catalog = create_catalog(&[(
            "* foo\n\
             * bar",
            "* FOO\n\
             * BAR\n\
             * BAZ",
        )]);
        assert_normalized_messages_eq(catalog, &[fuzzy("foo", "FOO"), fuzzy("bar", "BAR\n\nBAZ")]);
    }
```

This is what happened in https://github.com/google/comprehensive-rust/issues/1471 where we transform

```po
#: src/SUMMARY.md:92
msgid "Double Frees in Modern C++"
msgstr "آزاد سازی مضاعف در<span dir=ltr>C++</span> مدرن"
```

into

```po
#: src/SUMMARY.md:92
#, fuzzy
msgid "Double Frees in Modern C++"
msgstr ""
"آزاد سازی مضاعف در\n"
"\n"
"C++\n"
"\n"
"مدرن"
```

### PR DESCRIPTION
**Pull request by michael-kerscher**
Fixes #125 by keeping inline HTML tags in the translation text group but skip block level HTML tags.
This is possible with the upgrade of pulldown-cmark in #183

### CODE REVIEW

File: i18n-helpers/src/lib.rs [hunk 1]
```diff
@@ -367,14 +367,26 @@ pub fn group_events<'a>(events: &'a [(usize, Event<'a>)]) -> Vec<Group<'a>> {
...
-                    // Otherwise, treat as a skipping group.
                     _ => {
-                        if let State::Translate(_) = state {
-                            let mut next_groups;
-                            (next_groups, ctx) = state.into_groups(idx, events, ctx);
-                            groups.append(&mut next_groups);
-
-                            state = State::Skip(idx);
+                        // Otherwise, treat as a skipping group if this is a block level Html tag
+                        if matches!(event, Event::Html(_)) {
```
Comment (mgeisler) [inline i18n-helpers/src/lib.rs:372]: Could the `matches!` macro here be moved up into the `match` statement above?

That is, instead of a single match arm with

```rust
Event::Html(s) | Event::InlineHtml(s) => {
```

above, have separate `Event::Html(s)` and `Event::InlineHtml(s)` arms.

In general, the `matches!` macro is used rather rarely in Rust since the `match` or `if let` statements normally allow you to do the same thing.

Comment (michael-kerscher) [reply i18n-helpers/src/lib.rs:372]: I was hesitant to duplicate the directives::find() call and handling of Skip and Comment.
I'll give it another pass

**Comment by kdarkhan** [comment]
The fuzz step is failing due to some changes in rust nightly. The failure seems to occur from one of the dependencies.

Until the dependency is fixed, you can temporarily pin to specific nightly version by changing [this line](https://github.com/google/mdbook-i18n-helpers/blob/5b855b0eaf73f91b6a430a41baadf0ae846740f0/.github/workflows/test.yml#L116) to `rustup default nightly-2024-05-10`.

**Comment by kdarkhan** [comment]
The rules that determine whether the HTML is block or inline surprised me. I naively assumed that if a piece of HTML is on a separate line, then it is a block, and inline HTML otherwise. Turns out I was wrong. The rules are defined in https://spec.commonmark.org/0.31.2/#html-blocks. Some tags like `p` or `div` in a single line are considered to be blocks, while `span` is an inline.

Here is an [example](https://spec.commonmark.org/dingus/?text=%3Cdiv%3EThis%20is%20block%20because%20it%20is%20a%20div%3C%2Fdiv%3E%0A%0A%3Cspan%3EThis%20is%20inline%3C%2Fspan%3E%0A%0A%3Cspan%3E%3Cdiv%3EThis%20div%20is%20inline%3C%2Fdiv%3E%3C%2Fspan%3E%0A%0A%3Cspan%3E%0AThis%20is%20block%0A%3C%2Fspan%3E%0A%0AThis%20div%20%3Cdiv%3Enot%20block%3C%2Fdiv%3E%20because%20it%20is%20not%20starting%20the%20line.) which demonstrate how they differ. Switch to `AST` tab to view inlines vs blocks.

I believe even with above rules, not splitting inline elements into separate groups is an improvement.

File: i18n-helpers/src/lib.rs (hunk 1 above)
Comment (mgeisler) [reply i18n-helpers/src/lib.rs:372]: Ah, I see! I didn't think of that :smile: 

I think changing the two `matches!` calls here to a nested `match` statement would be a small improvement. The whole logic here is becoming a little complex and it could very well be ripe for some refactoring (in a later PR).

**Review by kdarkhan — APPROVED** [review]

File: .github/workflows/test.yml [hunk 2]
```diff
@@ -113,7 +113,7 @@ jobs:
         uses: actions/checkout@v4
 
       - name: Install nightly Rust
-        run: rustup default nightly
+        run: rustup default nightly-2024-05-10
```
Comment (mgeisler) [inline .github/workflows/test.yml:116]: I think it would be good to remind ourselves to remove this. Otherwise others will likely think that this is there for a specific reason.

Let's hope it's fixed in a month :smile: 

```suggestion
        # TODO: Unpin this after 2024-06-10
        run: rustup default nightly-2024-05-10
```

**Review by mgeisler — APPROVED** [review]
Thanks @michael-kerscher!

File: .github/workflows/test.yml (hunk 2 above)
Comment (kdarkhan) [reply .github/workflows/test.yml:117]: I just merged an update to `time` dep in https://github.com/google/mdbook-i18n-helpers/pull/198 and the workaround is no longer necessary.

Comment (michael-kerscher) [reply .github/workflows/test.yml]: I switched back to "nightly" only
